# Intro To Scikit-learn

Normal workflow:

1. Get Data Ready
2. Pick a model that suits the problem
3. Fit the model to the data and make a prediction
4. Evaluate the model
5. Improve through experimentation
6. Save and reload the trained model

In [1]:
# Standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


## 0. Quick Preview of Entire Workflow!

### 1. Get the Data Ready

In [6]:
# Import data and see what it looks like
heart_disease = pd.read_csv('data/heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [7]:
# We want to have the model guess `target` is 1 or 0, so we need variables
# Create X (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

### 2. Pick a model and hyperparameters that fit the problem

In [10]:
# Import classification model from sklearn
from sklearn.ensemble import RandomForestClassifier # Can classify data (1 or 0)
clf = RandomForestClassifier() # clf = classifier 

## Keep default hyperparameters
clf.get_params() # see model's hyperparameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

### 3. Fit the model to the data


In [11]:
# Split data into train and test sets
from sklearn.model_selection import train_test_split

# Split X (features) and y (labels) into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # test_size is % of rows that go into test set

In [12]:
# Tell sklearn to fit to the training data
clf.fit(X_train, y_train)

RandomForestClassifier()

In [14]:
# Make a predictions on the test set
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

### 4. Evaluate the Model

In [15]:
# How well has model predicted data on the training set?
clf.score(X_train, y_train) # 1.0 makes sense because it was trained on this data

1.0

In [17]:
# How well has the model predicted data on the test set?
clf.score(X_test, y_test) # output should probably be different from training predictions

0.8524590163934426

In [18]:
# Use some other measure to check the model's accuracy
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Classification Report
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.86      0.75      0.80        24
           1       0.85      0.92      0.88        37

    accuracy                           0.85        61
   macro avg       0.85      0.83      0.84        61
weighted avg       0.85      0.85      0.85        61



In [19]:
# Confusion Matrix
confusion_matrix(y_test, y_preds)

array([[18,  6],
       [ 3, 34]], dtype=int64)

In [20]:
# Accuracy Score
accuracy_score(y_test, y_preds)

0.8524590163934426

### 5. Improve the Model

Models can be improved by experimenting with tuning the hyperparameters

In [23]:
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model Accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 10 estimators...
Model Accuracy on test set: 80.33%

Trying model with 20 estimators...
Model Accuracy on test set: 90.16%

Trying model with 30 estimators...
Model Accuracy on test set: 85.25%

Trying model with 40 estimators...
Model Accuracy on test set: 85.25%

Trying model with 50 estimators...
Model Accuracy on test set: 88.52%

Trying model with 60 estimators...
Model Accuracy on test set: 88.52%

Trying model with 70 estimators...
Model Accuracy on test set: 86.89%

Trying model with 80 estimators...
Model Accuracy on test set: 85.25%

Trying model with 90 estimators...
Model Accuracy on test set: 85.25%



### 6. Save and Load Models
Use Python's pickle library

In [26]:
import pickle

### Save the Model

In [27]:
# Dump saves the model
# pass in the instantiated sklearn model object
# "wb" means write binary, or write the file contents
pickle.dump(clf, open("models/heart-disease-random-forest.pkl", "wb"))

### Load a Model

In [28]:
# "rb" means read binary
loaded_model = pickle.load(open("models/heart-disease-random-forest.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.8524590163934426

---

# In-Depth Sections

---

## 1. Getting the Data Ready
---

For the below steps, it's important to **run data transformations separately for training and testing sets**

Three main things to do:
- Split the data into features and labels (usually `X` and `y`)
- Split data into training and test sets (maybe 20% of data in test set)
- Filling (also called **imputing**) or disregarding missing values
- Converting non-numerical values to numerical values (AKA **feature encoding**)
- (Optional) Reduce the amount of data you use in the model
  - Also called **Dimensionality** reduction or column reduction
  - This can help save compute time and money by getting rid of data that might not be useful
- (Optional) **Feature Scaling** to make sure all the data is on the same scale so the ML model can find patterns. There are two main ways of doing this:
  - **Normalization (min-max scaling)**: Rescales all numerical values to be between 0 and 1. Scikit-learn has a library for this in the [MinMaxScalar class](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html)
  - **Standardization**: Subtracts the mean value from all features and then scales them by unit variance. Scikit-learn has a library for this in the [StandardScalar class](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)
  - Feature Scaling usually isn't required for your target variable
  - Feature scaling is not usually required with tree-based models (random forest) since they can handle varying features

In [30]:
# Still have this imported
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

### 1.1 - Split into Features and Labels

In [31]:
# Features do not include `target` column, which is whether or not the person has heart disease
X = heart_disease.drop("target", axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [32]:
# Label is the 'target' column
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [33]:
# Split data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Check shapes of data sets
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

### 1.2 - Convert All Data to Be Numeric



In [35]:
# Need data that has non-numeric data so we can practice changing it
car_sales = pd.read_csv("data/car-sales-extended.csv")
len(car_sales), car_sales.head()

(1000,
      Make Colour  Odometer (KM)  Doors  Price
 0   Honda  White          35431      4  15323
 1     BMW   Blue         192714      5  19943
 2   Honda  White          84714      4  28343
 3  Toyota  White         154365      4  13434
 4  Nissan   Blue         181577      3  14043)

In [36]:
# See that data is not in all numerics
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [64]:
# Turn the non-numeric categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Separate into X (features) and y (labels)
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# Prepare which features in your data are categorical and need to be transformed
# Note: "Doors" is categorical because you could split the data into groups by # of doors
categorical_features = ["Make", "Colour", "Doors"]

# Setup OneHotEncoder (see explanation below)
one_hot = OneHotEncoder()

# Setup transformer
# Tell it to use "one_hot" method with the one_hot object we created, and use it on the categorical_features we created
# Tell it to "passthrough" (skip, not tranform) columns that are already numeric
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

# Fit tranformed data
transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

#### One Hot Encoder

One Hot Encoder takes a single column that has categorical data in it, creates a new column for each unique category, and puts the data back into the data with a 1 in the unique column where it has a matching category. Here's an example graphic:

![](../images/one-hot-encoder.png)

In [65]:
# See transformed data in Pandas DataFrame
pd.DataFrame(transformed_X)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

#### Another Way to Convert with Pandas

This might not work on categorical data that is already in the form of numbers (like Doors in our example), but pandas does more intelligently name the columns so you can see what OneHotEncoding is doing

In [40]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [66]:
# Try to fit the model with converted data
np.random.seed(24)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

# Build and train model to predict car price
from sklearn.ensemble import RandomForestRegressor # Can predict a number (regression line)
model = RandomForestRegressor()

model.fit(X_train, y_train)
model.score(X_test, y_test)


0.2364711420373471

### 1.3 - Handle Missing Values in Data

Two main ways to deal with missing values:
1. Fill them with some other value (**imputation**)
2. Remove the samples with missing data

In [47]:
# Get some data that has missing values
car_sales_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [48]:
# Pandas fills missing values with `NaN`, so we can check if any of those exist
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

#### 1.3.1 - Fill Missing Data With Values (Imputation)
Pandas has ways to do this

In [49]:
# Fill the "Make" column
car_sales_missing["Make"].fillna("missing", inplace=True)

# Fill the "Colour" column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the "Odometer (KM)" column with mean of entire data set
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace=True)

# Fill the "Doors" column (assumption that average car has 4 doors)
car_sales_missing["Doors"].fillna(4, inplace=True)

# Check dataframe again
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

#### 1.3.2 Remove Missing Data Rows

In [50]:
# Remove rows with NaN values
# At this point there are only Price values missing. Since that's the target label, we don't
# necessarily want to try to fill it with other data
car_sales_missing.dropna(inplace=True)
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [57]:
# Resplit the data now that NaN values are gone
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

# Turn the non-numeric categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Prepare which features in your data are categorical and need to be transformed
# Note: "Doors" is categorical because you could split the data into groups by # of doors
categorical_features = ["Make", "Colour", "Doors"]

# Setup OneHotEncoder (see explanation below)
one_hot = OneHotEncoder()

# Setup transformer
# Tell it to use "one_hot" method with the one_hot object we created, and use it on the categorical_features we created
# Tell it to "passthrough" (skip, not tranform) columns that are already numeric
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

# Fit tranformed data
transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

#### 1.3.2 Filling Missing Values With Only Scikit-learn

In [68]:
# Reimport data so we have the missing values
car_sales_missing = pd.read_csv("data/car-sales-extended-missing-data.csv")
car_sales_missing.head(), car_sales_missing.isna().sum()

(     Make Colour  Odometer (KM)  Doors    Price
 0   Honda  White        35431.0    4.0  15323.0
 1     BMW   Blue       192714.0    5.0  19943.0
 2   Honda  White        84714.0    4.0  28343.0
 3  Toyota  White       154365.0    4.0  13434.0
 4  Nissan   Blue       181577.0    3.0  14043.0,
 Make             49
 Colour           50
 Odometer (KM)    50
 Doors            50
 Price            50
 dtype: int64)

In [70]:
# Remove rows that are missing "Price" since that's our target label and we don't want to guess at that
car_sales_missing.dropna(subset=["Price"], inplace=True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [71]:
# Split into X and y
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [72]:
# Fill missing values with Scikit-learn
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values with 'missing' and numerical values with mean
# Create imputer object with "constant" (always same) strategy and the value to fill it with
categorical_imputer = SimpleImputer(strategy="constant", fill_value="missing")

# "Doors" label is categorical but technically stored as numerical, so we make a special imputer for it
door_imputer = SimpleImputer(strategy="constant", fill_value=4)

# Create an imputer to fill the missing numerical values with the mean
num_imputer = SimpleImputer(strategy="mean")

# Define column names
categorical_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer to fill the missing values
# ColumnTransformer takes 3-tuples of imputer name, imputer object, column names
imputer = ColumnTransformer([
    ("categorical_imputer", categorical_imputer, categorical_features),
    ("door_imputer", door_imputer, door_features),
    ("num_imputer", num_imputer, num_features)
])

# Tranform the data
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [73]:
# Check that all values were filled by putting it into a Pandas DataFrame
car_sales_filled = pd.DataFrame(filled_X, columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head(), car_sales_filled.isna().sum()

(     Make Colour Doors Odometer (KM)
 0   Honda  White   4.0       35431.0
 1     BMW   Blue   5.0      192714.0
 2   Honda  White   4.0       84714.0
 3  Toyota  White   4.0      154365.0
 4  Nissan   Blue   3.0      181577.0,
 Make             0
 Colour           0
 Doors            0
 Odometer (KM)    0
 dtype: int64)

In [74]:
# Turn the non-numeric categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# Prepare which features in your data are categorical and need to be transformed
# Note: "Doors" is categorical because you could split the data into groups by # of doors
categorical_features = ["Make", "Colour", "Doors"]

# Setup OneHotEncoder (see explanation below)
one_hot = OneHotEncoder()

# Setup transformer
# Tell it to use "one_hot" method with the one_hot object we created, and use it on the categorical_features we created
# Tell it to "passthrough" (skip, not tranform) columns that are already numeric
transformer = ColumnTransformer([("one_hot", one_hot, categorical_features)], remainder="passthrough")

# Fit tranformed data
transformed_X = transformer.fit_transform(car_sales_filled)
transformed_X

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [75]:
# Now we have the data as all numbers and with filled values
# Let's fit a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.21990196728583944

## 2. Choosing the Right Estimator/Algorithm For Your Problem
---

Some things to note:
- SKlearn refers to machine learning models and algorithms as **estimators**
- Classification problem - predicting a category (hearth disease or not)
  - Sometimes you'll see `clf` (short for classifier) used as a classification estimator
- Regression Problem - predicting a number (selling price of a car)

[SKlearn has a map](https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) of what kind of model you should maybe look at using:
![](../images/ml_map.png)

**NOTE** - Some generalized tips:

1. If you have structured (tabled) data, use Ensemble methods
2. If you have unstructured data, use deep learning or transfer learning

### 2.1 - Picking a Machine Learning Model for a Regression Problem

Using the [California Housing dataset](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset)

In [81]:
# Get California Housing dataset
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [82]:
# Turn into Pandas DataFrame so it's easier to visualize
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [86]:
# Add target column onto dataframe
housing_df["target"] = housing["target"]
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [87]:
# Import algorithm
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(42)

# Create data
X = housing_df.drop("target", axis=1)
y = housing_df["target"] # median house price in $100,000s

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate and fit the model 
model = Ridge()
model.fit(X_train, y_train)

# Check the score of the model on (on the test set)
model.score(X_test, y_test)

0.5758549611440128

What if `Ridge` didn't work or didn't fit our needs?

We can try a different model from the scikit-learn algorithm map

Let's try an [Ensemble Model](https://scikit-learn.org/stable/modules/ensemble.html) (combination of smaller models)

In [88]:
# Import the RandomForestRegressor from the ensemble module
from sklearn.ensemble import RandomForestRegressor

# Setup random seed
np.random.seed(42)

# Create data
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create random forest model
model = RandomForestRegressor()
model.fit(X_train, y_train)

# Check the score of the model
model.score(X_test, y_test)

0.8065734772187598

### 2.2 Picking a Machine Learning Model on a Classification Data Set

In [90]:
# Get a classification problem data set
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

Consulting the map says to try `LinearSVC`, so let's do it

In [95]:
# Import the LinearSVC estimator class
from sklearn.svm import LinearSVC

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate LinearSVC
clf = LinearSVC(max_iter=10000)
clf.fit(X_train, y_train)

# Evaluate the LinearSVC
clf.score(X_test, y_test)

D:\Repos\ml-ds\learning-projects\env\lib\site-packages\sklearn\svm\_base.py:1206: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

Let's try RandomForestClassifier as well

In [96]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Evaluate the RandomForestClassifier
model.score(X_test, y_test)

0.8524590163934426

## 3. Fit the Model to the Data and Make Predictions
---

### 3.1 - Fitting the Model to the Data

Different names for:
- X = features, feature variables, data
- y = labels, targets, target variables

In [97]:
# Import the RandomForestClassifier estimator class
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make the data
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Fit the model to the data (training ML model)
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Evaluate the RandomForestClassifier (use the patterns the ML model has found)
model.score(X_test, y_test)

0.8524590163934426

### 3.2 - Making Predictions With ML Model

Two main ways to make predictions:
- predict()
- predict_proba()

#### 3.2.1 `Using predict()`

In [98]:
# Use a trained model to make predictions
model.predict(np.array[1, 7, 8, 3, 4]) # this doesn't work because the array doesn't match the data the model trained on

TypeError: 'builtin_function_or_method' object is not subscriptable

In [100]:
X_test.head(), X_test.shape

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 179   57    1   0       150   276    0        0      112      1      0.6   
 228   59    1   3       170   288    0        0      159      0      0.2   
 111   57    1   2       150   126    1        1      173      0      0.2   
 246   56    0   0       134   409    0        0      150      1      1.9   
 60    71    0   2       110   265    1        0      130      0      0.0   
 
      slope  ca  thal  
 179      1   1     1  
 228      1   0     3  
 111      2   1     3  
 246      1   2     3  
 60       2   1     2  ,
 (61, 13))

In [101]:
# Make predictions from test split
model.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [102]:
# Actual test labels
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [103]:
# Compare predictions to truth labels to evaluate the model
y_preds = model.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [104]:
# That comparison is the same as the built-in score function
model.score(X_test, y_test)

0.8524590163934426

In [105]:
# Another way to do it
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

#### 3.2.2 Using `predict_proba()`
`predict_proba()` returns probabilities of a classification label

In the example of the heart disease data we're using, the two classes are 0 (does not have heart disease) and 1 (has heart disease)

In [106]:
# See what it puts out
model.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [107]:
# Let's predict() on the same data
model.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

The above outputs are showing that the first five rows were put into the following classes with a certain probability. Index 0 was classified as 0 (no heart disease) with 89% probability of being correct and 11% of being wrong

You can see that `predict_proba()` to see which predictions the model was very confident in and which it wasn't. Using `predict()` forces the model to make a classification prediction, but it could only be 51% probable and that might be something to look at

`predict()` can also be used on Regression data. It'll make a prediction of a numerical value that you can compare to the test data. See below for an example

In [108]:
from sklearn.ensemble import RandomForestRegressor
np.random.seed(42)

# Create the data
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Split into sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model instance
model = RandomForestRegressor()

# Fit the model to the data
model.fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

In [109]:
# Compare predictions to actual values
y_preds[:10], np.array(y_test[:10])

(array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
        2.34323  , 1.66182  , 2.47489  , 4.8344779]),
 array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
        1.575  , 3.4    , 4.466  ]))

In [110]:
# Statistical Evaluation of predictions compared to truth
# Using Mean Absolute Error (average amount +/- the prediction was off the truth)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

0.32659871732073664

## 4. Evaluate the Model
---